### ISSUE TITLE
In-App Messaging

### ISSUE THREAD

**Issue by ItsTender** [ItsTender/CarSLN#9]
a new deticated messaging page, using the firebase messaging run service!

**Comment by yamenr** [comment]
Chat between users?

**Comment by ItsTender** [comment]
Exactly.
I won't rush it but i will try to add it before the end of the month.
Anyhow it will definitely be added even after 12th grade.

**Comment by yamenr** [comment]
🔥

**Comment by ItsTender** [comment]
The Messaging Feature has been Implemented in one single day, shows just how easy it is.......................
or is it LMAO 😂😂😂
